title: Wajeeh Khan # your name (or website title) here
logo: "/images/myprofile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  UMBC GES Student
  <br><br>
  <p><a href="https://wajeehk1.github.io/wajeehk/resume/cv.html">Resume</a>
  <br><br>
  <a href="https://www.linkedin.com/in/wajeeh-khan-26a4ba218/">Linkedin</a> 
  
theme: jekyll-theme-minimal
google_analytics: # your Google Analytics tracking ID here
