title: Wajeeh Khan # your name (or website title) here
logo: "/images/myprofile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  UMBC GES Student
  <br><br>
  Baltimore, MD 
  <br><br>
  <a href="https://www.linkedin.com/in/wajeeh-khan-26a4ba218/">Linkedin</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
