title: harrison deford # your name (or website title) here
logo: "/images/harrison.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  forklift certified; aspiring geographer
  <br><br>
  baltimore 
  <br><br>
  <a href="https://twitter.com/oonuttlet/">twitter</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
